language: php

php:
  - 5.5
  - 5.6

before_install:
  - bin/start_server.sh

before_script:
  - composer self-update
  - composer install
  - export LANG=C

script:
  - bin/behat -fprogress --strict

after_failure:
  - cat server.log
